In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# 1 Создание и изменение массивов
# Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте
# все элементы массива на 2, а затем замените все элементы больше 10 на 0.
# Выведите итоговый массив
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Создание массива

print("Изначальный массив: \n", a)

a = np.dot(a, 2) #Умножение элементов массива

print("Массив после умножения: \n", a)

a[a > 10] = 0 #Замена элементов массива

print("Итоговый массив: \n", a)


Изначальный массив: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Массив после умножения: 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
Итоговый массив: 
 [[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


In [ ]:
# 2 Работа с булевыми масками
# Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и
# выведите все элементы, которые делятся на 5 без остатка. Затем замените их на
# -1 и выведите обновленный массив
import numpy as np
a = np.random.randint(1, 100, 20) #Создание массива

print("Изначальный массив: \n", a)
print("Элементы, которые делятся на 5 без остатка: \n", a[a % 5 == 0])

a[a % 5 == 0] = -1 #Замена элементов

print("Итоговый массив: \n", a)

Изначальный массив: 
 [85 35 71 89 47 73 39 83 92 17 26 99 85 98 30 24 51 92  9 15]
Элементы, которые делятся на 5 без остатка: 
 [85 35 85 30 15]
Итоговый массив: 
 [-1 -1 71 89 47 73 39 83 92 17 26 99 -1 98 -1 24 51 92  9 -1]


In [ ]:
# 3 Объединение и разбиение массивов
# Создайте два массива NumPy размером 1×5, заполненные случайными числами
# от 0 до 50.
# Объедините эти массивы в один двумерный массив (по строкам).
# Разделите полученный массив на два массива, каждый из которых содержит 5
# элементов.
# Выведите все промежуточные и итоговые результаты.
import numpy as np
a = np.random.randint(0, 50, 5) #Создание массива
b = np.random.randint(0, 50, 5)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)

c = np.vstack((a, b)) #Объединение массивов

print("Объединённый массив c: \n", c)

c = c.flatten() #Превращение в одномерный массив
c1 = c[:len(c)//2]
c2 = c[len(c)//2:]

print("Разделённый массив c2: \n", c2)

Изначальный массив a: 
 [ 4 22 23  0  2]
Изначальный массив b: 
 [ 9 31 36 25 23]
Объединённый массив c: 
 [[ 4 22 23  0  2]
 [ 9 31 36 25 23]]
Разделённый массив c2: 
 [ 9 31 36 25 23]


In [ ]:
# 4 Генерация и работа с линейными последовательностями
# Создайте массив из 50 чисел, равномерно распределенных от -10 до 10.
# Вычислите сумму всех элементов, сумму положительных элементов и сумму
# отрицательных элементов. Выведите результаты.
import numpy as np

a = np.linspace(-10, 10, 50)

sum = np.sum(a)
sumpos = np.sum(a[a > 0])
sumotr = np.sum(a[a < 0])

print("Изначальный массив a: \n", a)
print("Сумма всех элементов: \n", sum)
print("Сумма положительных элементов: \n", sumpos)
print("Сумма отрицательных элементов: \n", sumotr)

Изначальный массив a: 
 [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов: 
 7.105427357601002e-15
Сумма положительных элементов: 
 127.55102040816328
Сумма отрицательных элементов: 
 -127.55102040816327


In [1]:
# 5 Работа с диагональными и единичными матрицами
# Создайте:
# Единичную матрицу размером 4×4.
# Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15,
# 20] (не использовать циклы).
# Найдите сумму всех элементов каждой из этих матриц и сравните результаты.
import numpy as np

a = np.eye(4)
b = np.diag([5, 10, 15, 20])

suma = np.sum(a)
sumb = np.sum(b)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Сумма положительных элементов: \n", suma)
print("Сумма отрицательных элементов: \n", sumb)

Изначальный массив a: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Изначальный массив b: 
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма положительных элементов: 
 4.0
Сумма отрицательных элементов: 
 50


In [ ]:
# 6 Создание и базовые операции с матрицами
# Создайте две квадратные матрицы NumPy размером 3×3, заполненные
# случайными целыми числами от 1 до 20. Вычислите и выведите:
# Их сумму
# Их разность
# Их поэлементное произведение
import numpy as np

a = np.random.randint(1, 20, (3, 3))
b = np.random.randint(1, 20, (3, 3))

sum = a + b
dif = a - b
mult = a * b

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Сумма массивов: \n", sum)
print("Разность массивов: \n", dif)
print("Поэлементное произведение массивов: \n", mult)

Изначальный массив a: 
 [[12 16 12]
 [17  3 10]
 [19 19 12]]
Изначальный массив b: 
 [[ 3  6  1]
 [ 6  4 11]
 [ 5 14  5]]
Сумма массивов: 
 [[15 22 13]
 [23  7 21]
 [24 33 17]]
Разность массивов: 
 [[ 9 10 11]
 [11 -1 -1]
 [14  5  7]]
Поэлементное произведение массивов: 
 [[ 36  96  12]
 [102  12 110]
 [ 95 266  60]]


In [ ]:
# 7 Умножение матриц
# Создайте две матрицы NumPy:
# Первую размером 2×3, заполненную случайными числами от 1 до 10.
# Вторую размером 3×2, заполненную случайными числами от 1 до 10.
# Выполните матричное умножение ( @ или np.dot ) и выведите результат.
import numpy as np

a = np.random.uniform(1, 10, (2, 3))
b = np.random.uniform(1, 10, (3,2))
c = np.dot(a, b)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Матричное умножение: \n", c)

Изначальный массив a: 
 [[5.78140493 7.70131096 9.57096924]
 [6.04376092 5.24598355 8.43024247]]
Изначальный массив b: 
 [[6.87744492 9.09298639]
 [1.25003437 9.33891071]
 [5.34998575 3.75383528]]
Матричное умножение: 
 [[100.59274629 160.41993366]
 [ 93.22496957 135.59334932]]


In [ ]:
# 8 Определитель и обратная матрица
# Создайте случайную квадратную матрицу 3×3. Найдите и выведите:
# Определитель этой матрицы
# Обратную матрицу (если существует, иначе выведите сообщение, что матрица
# вырождена)
# Используйте функции np.linalg.det и np.linalg.inv .
import numpy as np

a = np.random.randint(0, 10, (3, 3))

print("Изначальный массив a: \n", a)
print("Определитель: \n", np.linalg.det(a))

try:
  print("Обратная матрица: \n", np.linalg.inv(a))
except np.linalg.LinAlgError:
  print("Матрица вырождена\n")

Изначальный массив a: 
 [[1 9 3]
 [3 6 7]
 [4 1 3]]
Определитель: 
 119.00000000000003
Обратная матрица: 
 [[ 0.09243697 -0.20168067  0.37815126]
 [ 0.15966387 -0.07563025  0.01680672]
 [-0.17647059  0.29411765 -0.17647059]]


In [ ]:
# 9 Транспонирование и след матрицы
# Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от
# 1 до 50. Выведите:
# Исходную матрицу
# Транспонированную матрицу
# След матрицы (сумму элементов на главной диагонали)
# Используйте np.trace для нахождения следа.
import numpy as np

a = np.random.randint(0, 50, (4, 4))

print("Изначальный массив a: \n", a)
print("Транспонированная матрица: \n", a.transpose())
print("След матрицы: \n", np.trace(a))

Изначальный массив a: 
 [[11 48 26  1]
 [ 6 38  9 32]
 [38 38 22 36]
 [27 44 27 38]]
Транспонированная матрица: 
 [[11  6 38 27]
 [48 38 38 44]
 [26  9 22 27]
 [ 1 32 36 38]]
След матрицы: 
 109


In [ ]:
# 10 Системы линейных уравнений
# Решите систему линейных уравнений вида:
# 2x + 3y − z = 5
# 4x − y + 2z = 6
# −3x + 5y + 4z = −2
# Используйте матричное представление Ax = B , где A – матрица коэффициентов,
# x – вектор неизвестных, B – вектор правой части. Решите систему с помощью
# np.linalg.solve и выведите результат.
import numpy as np

A = np.array(([2, 3, -1], [4, -1, 2], [-3, 5, 4]))
B = np.array(([5, 6, -2]))
x = np.linalg.solve(A, B)

print("Решение системы \n")
print("x = :", x[0], "\n")
print("y = :", x[1], "\n")
print("z = :", x[2], "\n")

Решение системы 

x = : 1.6396396396396398 

y = : 0.5765765765765767 

z = : 0.009009009009008978 



In [ ]:
# 11 Индивидуальное задание
# Распределение воды по трубам. Вода поступает в три резервуара из общей
# системы труб. В первый резервуар поступает в два раза больше воды, чем во
# второй, а в третий — на 50 литров больше, чем во второй. Всего в систему
# поступает 500 литров воды. Сколько воды поступает в каждый резервуар?
import numpy as np

A = np.array(([1, -2, 0], [0, 1, -1], [1, 1, 1]))
B = np.array(([0, -50, 500]))
x = np.linalg.solve(A, B)

print("Решение системы \n")
print("x = :", x[0], "\n")
print("y = :", x[1], "\n")
print("z = :", x[2], "\n")

Решение системы 

x = : 225.0 

y = : 112.5 

z = : 162.5 

