In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# Создание и изменение массивов
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Создание массива

print("Изначальный массив: \n", a)

a = np.dot(a, 2) #Умножение элементов массива

print("Массив после умножения: \n", a)

a[a > 10] = 0 #Замена элементов массива

print("Итоговый массив: \n", a)


In [ ]:
# 2 Работа с булевыми масками
import numpy as np
a = np.random.randint(1, 100, 20) #Создание массива

print("Изначальный массив: \n", a)
print("Элементы, которые делятся на 5 без остатка: \n", a[a % 5 == 0])

a[a % 5 == 0] = -1 #Замена элементов

print("Итоговый массив: \n", a)

In [ ]:
# 3 Объединение и разбиение массивов
import numpy as np
a = np.random.randint(0, 50, 5) #Создание массива
b = np.random.randint(0, 50, 5)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)

c = np.vstack((a, b))

print("Объединённый массив c: \n", c)

c = c.flatten() #Превращение в одномерный массив
c1 = c[:len(c)//2]
c2 = c[len(c)//2:]

print("Разделённый массив c2: \n", c2)

In [ ]:
# 4 Генерация и работа с линейными последовательностями
import numpy as np

a = np.linspace(-10, 10, 50)

sum = np.sum(a)
sumpos = np.sum(a[a > 0])
sumotr = np.sum(a[a < 0])

print("Изначальный массив a: \n", a)
print("Сумма всех элементов: \n", sum)
print("Сумма положительных элементов: \n", sumpos)
print("Сумма отрицательных элементов: \n", sumotr)

Изначальный массив a: 
 [-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]
Сумма всех элементов: 
 7.105427357601002e-15
Сумма положительных элементов: 
 127.55102040816328
Сумма отрицательных элементов: 
 -127.55102040816327


In [ ]:
# 5 Работа с диагональными и единичными матрицами
import numpy as np

a = np.eye(4)
b = np.diag([5, 10, 15, 20])

suma = np.sum(a)
sumb = np.sum(b)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Сумма положительных элементов: \n", suma)
print("Сумма отрицательных элементов: \n", sumb)

Изначальный массив a: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Изначальный массив b: 
 [[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
Сумма положительных элементов: 
 4.0
Сумма отрицательных элементов: 
 50


In [ ]:
# 6 Создание и базовые операции с матрицами
import numpy as np

a = np.random.randint(1, 20, (3, 3))
b = np.random.randint(1, 20, (3, 3))

sum = a + b
dif = a - b
mult = a * b

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Сумма массивов: \n", sum)
print("Разность массивов: \n", dif)
print("Поэлементное произведение массивов: \n", mult)

Изначальный массив a: 
 [[12 16 12]
 [17  3 10]
 [19 19 12]]
Изначальный массив b: 
 [[ 3  6  1]
 [ 6  4 11]
 [ 5 14  5]]
Сумма массивов: 
 [[15 22 13]
 [23  7 21]
 [24 33 17]]
Разность массивов: 
 [[ 9 10 11]
 [11 -1 -1]
 [14  5  7]]
Поэлементное произведение массивов: 
 [[ 36  96  12]
 [102  12 110]
 [ 95 266  60]]


In [ ]:
# 7 Умножение матриц
import numpy as np

a = np.random.uniform(1, 10, (2, 3))
b = np.random.uniform(1, 10, (3,2))
c = a @ b
cs = np.dot(a, b)

print("Изначальный массив a: \n", a)
print("Изначальный массив b: \n", b)
print("Матричное умножение: \n", c)
cs

Изначальный массив a: 
 [[9.7282936  4.63074228 1.45456957]
 [3.74091995 7.71524091 7.63492642]]
Изначальный массив b: 
 [[6.69831372 6.96941676]
 [1.30634662 1.46340978]
 [9.45432586 2.06233045]]
Матричное умножение: 
 [[ 84.96449168  77.57700909]
 [107.31971664  53.10833041]]


array([[ 84.96449168,  77.57700909],
       [107.31971664,  53.10833041]])

In [22]:
# 8 Определитель и обратная матрица
import numpy as np

a = np.random.randint(0, 10, (3, 3))

print("Изначальный массив a: \n", a)
print("Определитель: \n", np.linalg.det(a))

try:
  print("Обратная матрица: \n", np.linalg.inv(a))
except np.linalg.LinAlgError:
  print("Матрица вырождена\n")

Изначальный массив a: 
 [[1 9 3]
 [3 6 7]
 [4 1 3]]
Определитель: 
 119.00000000000003
Обратная матрица: 
 [[ 0.09243697 -0.20168067  0.37815126]
 [ 0.15966387 -0.07563025  0.01680672]
 [-0.17647059  0.29411765 -0.17647059]]


In [26]:
# 9 Транспонирование и след матрицы
import numpy as np

a = np.random.randint(0, 50, (4, 4))

print("Изначальный массив a: \n", a)
print("Транспонированная матрица: \n", a.transpose())
print("След матрицы: \n", np.trace(a))

Изначальный массив a: 
 [[11 48 26  1]
 [ 6 38  9 32]
 [38 38 22 36]
 [27 44 27 38]]
Транспонированная матрица: 
 [[11  6 38 27]
 [48 38 38 44]
 [26  9 22 27]
 [ 1 32 36 38]]
След матрицы: 
 109


In [38]:
# 10 Системы линейных уравнений
import numpy as np

A = np.array(([2, 3, -1], [4, -1, 2], [-3, 5, 4]))
B = np.array(([5, 6, -2]))
x = np.linalg.solve(A, B)

print("Решение системы \n")
print("x = :", x[0], "\n")
print("y = :", x[1], "\n")
print("z = :", x[2], "\n")

Решение системы 

x = : 1.6396396396396398 

y = : 0.5765765765765767 

z = : 0.009009009009008978 



In [40]:
# 11 Индивидуальное задание
import numpy as np

A = np.array(([1, -2, 0], [0, 1, -1], [1, 1, 1]))
B = np.array(([0, -50, 500]))
x = np.linalg.solve(A, B)

print("Решение системы \n")
print("x = :", x[0], "\n")
print("y = :", x[1], "\n")
print("z = :", x[2], "\n")

Решение системы 

x = : 225.0 

y = : 112.5 

z = : 162.5 

